# Generated by Django 4.1.7 on 2023-03-03 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fa_model',
            name='News_Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 3, 19, 31, 18, 491158)),
        ),
    ]
