# Generated by Django 4.1.7 on 2023-03-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slide_Image_Logo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide_model',
            name='Slide_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
