# Generated by Django 4.1.7 on 2023-03-03 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_rename_waye_team_manager_name_game_model_way_team_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_model',
            name='Game_Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 3, 20, 52, 42, 729934)),
        ),
    ]
