# Generated by Django 4.1.7 on 2023-03-03 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_alter_game_model_game_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_model',
            name='is_game_finished',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='game_model',
            name='Game_Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 0, 59, 5, 347995)),
        ),
    ]
